[package]
name = "deeplearn"
version = "0.1.0"
authors = ["Theodore DeRego <tderego94@gmail.com>"]
edition = "2018"

[dependencies.wgpu-array]
path = "../gpu/wgpu-array"

[dependencies]
rand = "*"
num = "*"
futures-channel-preview = { version="0.3.0-alpha.18" }
ndarray = "0.12.1"
